name: Build Android App

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install mobile dependencies
      working-directory: ./mobile
      run: npm install
    
    - name: Install EAS CLI
      run: npm install -g eas-cli
    
    - name: Build Android AAB with EAS
      working-directory: ./mobile
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: eas build --platform android --profile production --non-interactive
    
    - name: Download built AAB
      working-directory: ./mobile
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: |
        BUILD_ID=$(eas build:list --platform android --limit 1 --json --non-interactive | jq -r '.[0].id')
        eas build:download --id $BUILD_ID --output ./app-release.aab
    
    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: app-release-aab
        path: mobile/app-release.aab
        retention-days: 30
